#!/bin/bash
my_opt_flags="
-faggressive-loop-optimizations
-falign-functions=16
-falign-jumps=16:11:8
-falign-labels=0:0:8
-falign-loops=16:11:8
-fallocation-dce
-fasynchronous-unwind-tables
-fauto-inc-dec
-fbit-tests
-fbranch-count-reg
-fcaller-saves
-fcode-hoisting
-fcombine-stack-adjustments
-fcompare-elim
-fcprop-registers
-fcrossjumping
-fcse-follow-jumps
-fcse-skip-blocks
-fdce
-fdefer-pop
-fdevirtualize
-fdevirtualize-speculatively
-fdse
-fearly-inlining
-fexpensive-optimizations
-ffold-mem-offsets
-fforward-propagate
-ffp-int-builtin-inexact
-ffunction-cse
-fgcse
-fgcse-lm
-fguess-branch-probability
-fhoist-adjacent-loads
-fif-conversion
-fif-conversion2
-findirect-inlining
-finline
-finline-atomics
-finline-functions
-finline-functions-called-once
-finline-small-functions
-fipa-bit-cp
-fipa-cp
-fipa-icf
-fipa-icf-functions
-fipa-icf-variables
-fipa-modref
-fipa-profile
-fipa-pure-const
-fipa-ra
-fipa-reference
-fipa-reference-addressable
-fipa-sra
-fipa-stack-alignment
-fipa-strict-aliasing
-fipa-vrp
-fira-hoist-pressure
-fira-share-save-slots
-fira-share-spill-slots
-fisolate-erroneous-paths-dereference
-fivopts
-fjump-tables
-flifetime-dse
-flra-remat
-fmath-errno
-fmerge-constants
-fmove-loop-invariants
-fmove-loop-stores
-fno-inline-stringops
-fomit-frame-pointer
-foptimize-sibling-calls
-foptimize-strlen
-fpartial-inlining
-fpeephole
-fpeephole2
-fplt
-fprintf-return-value
-free
-freg-struct-return
-freorder-blocks
-freorder-blocks-and-partition
-freorder-functions
-frerun-cse-after-loop
-fsched-critical-path-heuristic
-fsched-dep-count-heuristic
-fsched-group-heuristic
-fsched-interblock
-fsched-last-insn-heuristic
-fsched-rank-heuristic
-fsched-spec
-fsched-spec-insn-heuristic
-fsched-stalled-insns-dep
-fschedule-fusion
-fschedule-insns
-fschedule-insns2
-fsemantic-interposition
-fset-stack-executable
-fshort-enums
-fshrink-wrap
-fshrink-wrap-separate
-fsigned-zeros
-fsplit-ivs-in-unroller
-fsplit-wide-types
-fssa-backprop
-fssa-phiopt
-fstdarg-opt
-fstore-merging
-fstrict-aliasing
-fthread-jumps
-ftoplevel-reorder
-ftrapping-math
-ftree-bit-ccp
-ftree-builtin-call-dce
-ftree-ccp
-ftree-ch
-ftree-coalesce-vars
-ftree-copy-prop
-ftree-dce
-ftree-dominator-opts
-ftree-dse
-ftree-forwprop
-ftree-fre
-ftree-loop-distribute-patterns
-ftree-loop-im
-ftree-loop-ivcanon
-ftree-loop-optimize
-ftree-loop-vectorize
-ftree-phiprop
-ftree-pre
-ftree-pta
-ftree-reassoc
-ftree-scev-cprop
-ftree-sink
-ftree-slp-vectorize
-ftree-slsr
-ftree-sra
-ftree-switch-conversion
-ftree-tail-merge
-ftree-ter
-ftree-vrp
-funroll-loops
-funwind-tables
-fvect-cost-model=very-cheap
"

my_regular_flags="
-Wno-cpp
-Wl,-eentry
-nostdlib
-mno-red-zone
-m64
-mfpmath=sse
-mno-mmx
-mavx
-include ./include/arm_cpu_ctx.h
-ffreestanding
-ftime-report
-fno-gcse
"

my_params="
max-crossjump-edges=64
min-crossjump-insns=3
max-goto-duplication-insns=8
"

my_opt_flags_clean=$(echo -e "$my_opt_flags" | tr '\n' ' ')
my_regular_flags_clean=$(echo -e "$my_regular_flags" | tr '\n' ' ')
# my_params_clean=$(echo -e "$my_params" | sed -e 's/^/--param/' | tr '\n' ' ')
my_params_clean=$(echo -e "$my_params" | grep -v '^$' | sed -e 's/^/--param /' | tr '\n' ' ')

# gcc -o "$1.elf" -O2 -Wl,-eentry -nostdlib -mno-red-zone -m64 -mfpmath=sse -mno-mmx -mavx -ffreestanding "-Wa,-adhln=$1.gen.s" -fverbose-asm -masm=intel -include "include/arm_cpu_ctx.h" -c "$1.src.c"
# gcc -o "$1.elf" $my_regular_flags_clean $my_opt_flags_clean $my_params_clean -c "$1.src.c"
gcc -o "$1.elf" $my_regular_flags_clean -O2 $my_params_clean -c "$1.src.c"
#  -Wl,--section-start=.text=0x400000000
